---
driver:
  name: vagrant
  vm_hostname: neutron.ci.local
  use_sudo: false
  customize:
    memory: 512


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  formula: neutron
  log_level: info
  state_top:
    base:
      "*":
        - neutron
  pillars:
    top.sls:
      base:
        "*":
          - neutron
  grains:
    noservices: False


verifier:
  name: inspec
  sudo: true


platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  #- name: centos-7.1


suites:

  - name: control-cluster
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_cluster.sls

  - name: control-single
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_single.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
